"""Per-entity stable-era detection — series building, change-point detection, ensemble.

Pipeline seam (epic-stable-era-windows-detection):

    series.py    build_entity_series(con)          -> dict[str, EntitySeries]   (the only DB pass)
    detect.py    detect_presence / detect_composition / detect_share
                 + corroborate_winrate             -> list[CandidateBoundary]   (pure numpy)
    ensemble.py  derive_eras(series, candidates)   -> dict[str, EntityEras]     (merge + BH-FDR
                                                       + deck floor + camp inheritance)
    bocpd.py     beta_binomial_bocpd               -> BocpdResult               (online drift
                                                       alarm; consumed by the era-ledger feature)
"""

from __future__ import annotations

from legacy_engine.analytics.eras.bocpd import BocpdResult, beta_binomial_bocpd
from legacy_engine.analytics.eras.detect import (
    SIGNAL_TYPES,
    CandidateBoundary,
    corroborate_winrate,
    detect_composition,
    detect_presence,
    detect_share,
)
from legacy_engine.analytics.eras.ensemble import EntityEras, EraBoundary, derive_eras
from legacy_engine.analytics.eras.series import Bucket, EntitySeries, build_entity_series
from legacy_engine.analytics.eras.discovery import (
    DiscoveryBoundary,
    DiscoveryCalibration,
    DiscoveryCard,
    DiscoveryDeck,
    DiscoveryReason,
    DiscoveryStatus,
    DistanceThresholds,
    EntityDiscoveryResult,
    NamedMass,
    OutcomeFreeCorpus,
    OutcomeFreeModel,
    RecurrentCandidateGroup,
    SegmentComparison,
    SegmentDistances,
    SegmentFingerprint,
    SegmentSupport,
    SegmentationWeights,
    compare_segment_fingerprints,
    discover_recurrent_states,
    load_discovery_calibration,
    load_outcome_free_corpus,
    segment_parent_archetype,
)
from legacy_engine.analytics.eras.discovery_run import (
    DISCOVERY_FEATURE_ALLOWLIST,
    DiscoveryManifest,
    DiscoveryRun,
    build_discovery_manifest,
    run_recurrent_discovery,
)
from legacy_engine.analytics.eras.discovery_store import (
    discovery_run_ids,
    init_discovery_schema,
    read_discovery_run,
    write_discovery_run,
)
from legacy_engine.analytics.eras.certification import (
    CandidateCertificationInput,
    CandidateDecision,
    CertificationCalibration,
    CertificationReason,
    CertificationStatus,
    ContextOverlapEvidence,
    EquivalenceBand,
    EquivalenceEvidence,
    EventPartitionPlan,
    GateDisposition,
    HalfOpenInterval,
    PartitionManifest,
    PartitionedOutcomeFreeCorpus,
    SemanticFact,
    SemanticFactKind,
    SemanticFactState,
    SemanticGuardEvidence,
    SupportEvidence,
    build_candidate_inputs,
    certify_candidate_family,
    estimate_candidate_discrepancies,
    evaluate_context_overlap,
    evaluate_semantic_guards,
    evaluate_support,
    load_certification_calibration,
    load_certification_corpus,
    partition_outcome_free_corpus,
    partition_role,
)
from legacy_engine.analytics.eras.certification_run import (
    CERTIFICATION_FEATURE_ALLOWLIST,
    CertificationManifest,
    CertificationRun,
    EntityCertificationResult,
    EraCertificate,
    run_recurrent_certification,
)
from legacy_engine.analytics.eras.certificate_store import (
    certification_run_ids,
    init_certificate_schema,
    read_certification_run,
    write_certification_run,
)
from legacy_engine.analytics.eras.consume import (
    AnalysisClock,
    EligibilityAtom,
    EligibilitySourceRef,
    EntityEligibility,
    EvidenceConcentration,
    MatchupEvidenceView,
    MatchupEvidenceViews,
    PriorEvidenceAudit,
    build_entity_eligibility,
    build_evidence_views,
    intersect_atoms,
    normalize_atoms,
)

__all__ = [
    "Bucket",
    "EntitySeries",
    "build_entity_series",
    "BocpdResult",
    "beta_binomial_bocpd",
    "SIGNAL_TYPES",
    "CandidateBoundary",
    "detect_presence",
    "detect_composition",
    "detect_share",
    "corroborate_winrate",
    "EraBoundary",
    "EntityEras",
    "derive_eras",
    "OutcomeFreeModel",
    "DiscoveryCard",
    "DiscoveryDeck",
    "DiscoveryBoundary",
    "DistanceThresholds",
    "SegmentationWeights",
    "DiscoveryCalibration",
    "OutcomeFreeCorpus",
    "NamedMass",
    "SegmentSupport",
    "SegmentFingerprint",
    "SegmentDistances",
    "SegmentComparison",
    "RecurrentCandidateGroup",
    "EntityDiscoveryResult",
    "DiscoveryStatus",
    "DiscoveryReason",
    "load_discovery_calibration",
    "load_outcome_free_corpus",
    "segment_parent_archetype",
    "compare_segment_fingerprints",
    "discover_recurrent_states",
    "DISCOVERY_FEATURE_ALLOWLIST",
    "DiscoveryManifest",
    "DiscoveryRun",
    "build_discovery_manifest",
    "run_recurrent_discovery",
    "init_discovery_schema",
    "write_discovery_run",
    "read_discovery_run",
    "discovery_run_ids",
    "EventPartitionPlan",
    "PartitionManifest",
    "PartitionedOutcomeFreeCorpus",
    "CertificationCalibration",
    "HalfOpenInterval",
    "SemanticFact",
    "SemanticFactKind",
    "SemanticFactState",
    "GateDisposition",
    "CertificationStatus",
    "CertificationReason",
    "CandidateCertificationInput",
    "SemanticGuardEvidence",
    "SupportEvidence",
    "ContextOverlapEvidence",
    "EquivalenceBand",
    "EquivalenceEvidence",
    "CandidateDecision",
    "load_certification_calibration",
    "partition_role",
    "partition_outcome_free_corpus",
    "load_certification_corpus",
    "build_candidate_inputs",
    "evaluate_semantic_guards",
    "evaluate_support",
    "evaluate_context_overlap",
    "estimate_candidate_discrepancies",
    "certify_candidate_family",
    "CERTIFICATION_FEATURE_ALLOWLIST",
    "EraCertificate",
    "EntityCertificationResult",
    "CertificationManifest",
    "CertificationRun",
    "run_recurrent_certification",
    "init_certificate_schema",
    "write_certification_run",
    "read_certification_run",
    "certification_run_ids",
    "AnalysisClock",
    "EligibilityAtom",
    "EligibilitySourceRef",
    "EntityEligibility",
    "EvidenceConcentration",
    "PriorEvidenceAudit",
    "MatchupEvidenceView",
    "MatchupEvidenceViews",
    "normalize_atoms",
    "intersect_atoms",
    "build_entity_eligibility",
    "build_evidence_views",
]
